# Creates a trinityCore server for both auth and world server
FROM ubuntu:21.10

### squelches tzdata's install prompt
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y \
     apt-utils \
     less \
     nano \
     vim \
     make \
     mariadb-client \
#     libmariadbclient-dev \
     sudo \
     systemctl \
     git \
     clang \
     cmake \
     make \
     gcc \
     g++ \
     libmariadb-dev \
     libmariadb-dev-compat \
     libssl-dev \
     libbz2-dev \
     libreadline-dev \
     libncurses-dev \
     libboost-all-dev \
     mariadb-server \
     p7zip \
     libmariadb-client-lgpl-dev-compat

#    && adduser -q -u 1000 trinitycore
COPY . /srv/wow/trinitycore/3.3.5a

###
ENV DEBIAN_FRONTEND=

# by default, this containers will idle and do nothing. This is needed to easily run Trinity in "attended" mode
# when creating a clean server instance. Set the TrinityCore start process from Docker-compose file.
# See README.md for details
CMD ["/bin/bash", "-c", "while true ;sleep 5; do continue; done"]
